apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cdk8s-poc-workers
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: hello-go
                - name: hello-java
          - list:
              elements:
                - env: dev
                  cluster: DevCluster
                  namespace: hello-dev
                - env: prod
                  cluster: ProdCluster
                  namespace: hello-prod
  template:
    metadata:
      name: '{{name}}-{{env}}-cdk8s'
    spec:
      project: default
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      source:
        repoURL: https://example.com/cdk8s-poc.git
        targetRevision: HEAD
        path: cdk8s-poc/dist/{{env}}/{{name}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
